### PR TITLE
GH-83: readable, unescaped error stacktraces in logs.

### LINKED ISSUE #83: Readable stacktraces in logs
Currently, stacktraces are logged as json fields. Escaped and unreadable.
Propose hack zap logging a bit, to write them as unescaped text after log line

### PR DESCRIPTION
**Pull request by skipor**
Fixes #83.

### CODE REVIEW

File: lib/zaputil/stack_extact_core.go [hunk 1]
```diff
@@ -0,0 +1,164 @@
+// Copyright (c) 2018 Yandex LLC. All rights reserved.
```
Comment (direvius) [inline lib/zaputil/stack_extact_core.go]: typo in filename: stack_extact_core instead of stack_extRact_core

Comment (skipor) [reply lib/zaputil/stack_extact_core.go]: fixed
